services:
  guacd:
    image: guacamole/guacd:1.6.0
    container_name: ${CONTAINER_NAME}-guacd
    restart: always
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"

  guacamole:
    image: guacamole/guacamole:1.6.0
    container_name: ${CONTAINER_NAME}
    restart: always
    depends_on:
      guacd:
        condition: service_started
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:8080
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: ${PANEL_DB_HOST}
      MYSQL_PORT: ${PANEL_DB_PORT}
      MYSQL_DATABASE: ${PANEL_DB_NAME}
      MYSQL_USERNAME: ${PANEL_DB_USER}
      MYSQL_PASSWORD: ${PANEL_DB_USER_PASSWORD}
      WEBAPP_CONTEXT: ROOT
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
