services:
  yacd:
    image: haishanh/yacd:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    ports:
      - ${PANEL_APP_PORT_HTTP}:80
    environment:
      - TZ=${TIME_ZONE}
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true